import { AppV1_Typography, AppV1_Image, AppV1_Space, AppV1_Button, AppV1_List, AppV1_Frame } from '@party-opu/funii-assist-types';
export declare const typography1: AppV1_Typography;
export declare const typography2: AppV1_Typography;
export declare const typography3: AppV1_Typography;
export declare const image1: AppV1_Image;
export declare const image2: AppV1_Image;
export declare const space1: AppV1_Space;
export declare const space2: AppV1_Space;
export declare const space3: AppV1_Space;
export declare const button1: AppV1_Button;
export declare const button2: AppV1_Button;
export declare const button3: AppV1_Button;
export declare const button4: AppV1_Button;
export declare const button5: AppV1_Button;
export declare const button6: AppV1_Button;
export declare const testItems: {
    id: string;
    'columnID-1': string;
    'columnID-2': string;
    'columnID-3': string;
}[];
export declare const list1: AppV1_List;
export declare const list2: AppV1_List;
export declare const list3: AppV1_List;
export declare const list4: AppV1_List;
export declare const frame1: AppV1_Frame;
export declare const frame2: AppV1_Frame;
export declare const frame3: AppV1_Frame;
export declare const frame4: AppV1_Frame;
//# sourceMappingURL=node.d.ts.map